server:
  port: 8084

spring:
  application:
    name: campaign-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/campaigndb
    username: ${DB_USER:USER_NAME}
    password: ${DB_PASS:YOUR_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

jwt:
  secret: ${JWT_SECRET:YOUR_JWT_SECRET}
  
services:
  contact-service:
    url: ${CONTACT_SERVICE_URL:http://localhost:8083}

logging:
  level:
    com.nic.campaign: DEBUG