server:
  port: 8888

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG