version: '3.8'

services:
  messaging-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nic-messaging-service
    ports:
      - "8085:8085"
    environment:
      DB_HOST: nic-postgres
      DB_USER: postgres
      DB_PASS: YOUR_POSTGRESS_PASSWORD
      JWT_SECRET: YOUR_JWT_SECRET_KEY
      RABBITMQ_HOST: nic-rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      MAIL_USERNAME: YOUR_MAIL@email.com
      MAIL_PASSWORD: YOUR_GMAIL_APP_PASSWORD
      CONTACT_SERVICE_URL: http://nic-contact-service:8083
      CAMPAIGN_SERVICE_URL: http://nic-campaign-service:8084
      BILLING_SERVICE_URL: http://nic-billing-service:8086
    networks:
      - nic-network
    restart: on-failure

networks:
  nic-network:
    external: true