version: '3.8'

services:
  campaign-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nic-campaign-service
    ports:
      - "8084:8084"
    environment:
      DB_HOST: nic-postgres
      DB_USER: postgres
      DB_PASS: YOUR_POSTGRESS_PASSWORD
      JWT_SECRET: YOUR_JWT_SECRET_KEY
      RABBITMQ_HOST: nic-rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      CONTACT_SERVICE_URL: http://nic-contact-service:8083
    networks:
      - nic-network
    restart: on-failure

networks:
  nic-network:
    external: true